### ISSUE TITLE
Specify Python version to avoid 3.13 in workflows

### ISSUE THREAD

**Issue by bact** [spdx/spdx-spec#1135]
- Python 3.13 releases on 7 Oct 2024 and no longer has the `cgi` module.
  - This will break every workflows that install requirements.txt and use `container: python:3`, since "3" is now "3.13".
- Our requirements.txt (in development/v3.0.1 branch) has
  - json-schema-for-humans==1.0.2
    - which requires htmlmin-0.1.12.tar.gz
      - which uses a `cgi` module - https://github.com/mankyd/htmlmin/issues/66

## To prevent the break

- Specify Python version to 3.12 or lower, using either
  - `container: python:3.12` ; or
  - `actions/setup-python`: 
    ```yaml
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  #v5.2.0
      with:
        python-version: "3.12"
        cache: "pip"
    ```
- Alternatively, we can wait json-schema-for-humans to update - https://github.com/coveooss/json-schema-for-humans/issues/269
