### ISSUE TITLE
Use simpler notation for ExternalRefs in JSON, YAML and XML

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#156]
In the [SPDX 2.2 YAML example](https://github.com/spdx/spdx-spec/blob/development/v2.2/examples/SPDXYAMLExample-2.0.yaml) I found 

```
externalRefs:
  - referenceCategory: "referenceCategory_security"
    referenceType:
      referenceTypeUri: "http://spdx.org/rdf/references/cpe23Type"
    referenceLocator: "cpe:2.3:a:pivotal_software:spring_framework:4.1.0:*:*:*:*:*:*:*"
    comment: null
 ```

which seems to based on below RDF example in the SPDX 2.1 spec
```
<spdx:externalRef>
  <spdx:ExternalRef>
    <spdx:referenceCategory rdf:resouce=”http://spdx.org/rdf/terms#referenceCategory_packageManager” />
    <spdx:referenceType rdf:resource=”http://spdx.org/rdf/refeferences/maven-central” />
    <spdx:referenceLocator>org.apache.commons:commons-lang:3.2.1</spdx:referenceLocator>
  </spdx:ExternalRef>
</spdx:externalRef>
```
Propose to simplify the format for ExternalRef to:

```
externalRefs:
 - category: "SECURITY"
    type: "cpe23Type"
    locator: "cpe:2.3:a:pivotal_software:spring_framework:4.1.0:*:*:*:*:*:*:*"
    comment: ""
```
