### ISSUE TITLE
Simplify Snippet Ranges representation in YAML/JSON

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#412]
In SPDX 2.2 example [Snippet Byte Range](https://github.com/spdx/spdx-spec/blob/master/chapters/5-snippet-information.md#53-snippet-byte-range-) and [Snippet Line Range](https://github.com/spdx/spdx-spec/blob/master/chapters/5-snippet-information.md#54-snippet-line-range-) are currently encoded as RDF (see below code) but elswhere we consistently followed SPDX `tag:value`. Propose to align ranges wit `tag:value` for consistecy and make adoption/generation easier.

```
    ranges:
    - endPointer:
        offset: 420
        reference: "SPDXRef-DoapSource"
      startPointer:
        offset: 310
        reference: "SPDXRef-DoapSource"
    - endPointer:
        lineNumber: 23
        reference: "SPDXRef-DoapSource"
      startPointer:
        lineNumber: 5
        reference: "SPDXRef-DoapSource"
```
Change to:

```
SnippetByteRange: "310:420"
SnippetLineRange: "5:23"
```
