### ISSUE TITLE
Remove string parsing requirement for select SPDX elements

### ISSUE THREAD

**Issue by tsteenbe** [spdx/spdx-spec#424]
Several SPDX elements require string parsing to get the value specified by its creator see code examples below. In SPDX 3.0 we should simplify things and remove the need to do string parsing across element. This new ticket is a follow-up on discussions with @goneall  @swinslow  in https://github.com/spdx/spdx-spec/issues/412.

**Document Creator**

```
<CreationInfo>
    <creator>Person: Jane Doe () </creator>
    <creator>Organization: ExampleCodeInspect () </creator>
    <creator>Tool: LicenseFind-1.0 </creator>
</CreationInfo>
```

SPDX 3.0 proposal by @swinslow 

```
"creators": [ {"type": "TOOL", "value": "LicenseFind-1.0"}, ... ]
```

**Annotations**

```
annotations:
- annotationDate: "2011-03-13T00:00:00Z"
   annotationType: "REVIEW"
   annotator: "Person: Suzanne Reviewer"
   comment: "Another example reviewer."
- annotationDate: "2010-01-29T18:30:22Z"
   annotationType: "OTHER"
   annotator: "Person: Jane Doe ()"
   comment: "Document level annotation"
```

SPDX 3.0 proposal by @tsteenbe:

```
annotations:
-  date: "2011-03-13T00:00:00Z"
   type: "REVIEW"
   annotator:
       - type: "PERSON"
          value: "Suzanne Reviewer"
          email: "suzanne@example.com"
   comment: "Another example reviewer."
- date: "2010-01-29T18:30:22Z"
   type: "OTHER"
   annotator:
       - type: "PERSON"
          value: "Jane Doe"
   comment: "Document level annotation"
```
